//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conteudo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conteudo()
        {
            this.ConteudoImagem = new HashSet<ConteudoImagem>();
            this.ConteudoVideo = new HashSet<ConteudoVideo>();
            this.ProgramacaoAgendamento = new HashSet<ProgramacaoAgendamento>();
        }
    
        public long ConteudoID { get; set; }
        public Nullable<long> EmpresaID { get; set; }
        public string Designacao { get; set; }
        public short Tipo { get; set; }
        public string QRCode { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteudoImagem> ConteudoImagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConteudoVideo> ConteudoVideo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramacaoAgendamento> ProgramacaoAgendamento { get; set; }
    }
}
