//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteudoImagem
    {
        public long ConteudoImagemID { get; set; }
        public long ConteudoID { get; set; }
        public string UrlImagem { get; set; }
        public int Duracao { get; set; }
        public string Extensao { get; set; }
        public byte[] Imagem { get; set; }
        public byte[] HashFicheiro { get; set; }
        public string Designacao { get; set; }
        public Nullable<int> Ordem { get; set; }
    
        public virtual Conteudo Conteudo { get; set; }
    }
}
