//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conteudo> Conteudo { get; set; }
        public virtual DbSet<ConteudoImagem> ConteudoImagem { get; set; }
        public virtual DbSet<ConteudoVideo> ConteudoVideo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaModulo> EmpresaModulo { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<LogErro> LogErro { get; set; }
        public virtual DbSet<LogEvento> LogEvento { get; set; }
        public virtual DbSet<Programacao> Programacao { get; set; }
        public virtual DbSet<ProgramacaoAgendamento> ProgramacaoAgendamento { get; set; }
        public virtual DbSet<Tv> Tv { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
    }
}
