//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEvento
    {
        public long LogEventoID { get; set; }
        public int EventoID { get; set; }
        public long UtilizadorID { get; set; }
        public string Tabela { get; set; }
        public string Campo { get; set; }
        public string Identificador { get; set; }
        public string ValorNovo { get; set; }
        public string ValorAnterior { get; set; }
        public System.DateTime DataHora { get; set; }
    }
}
