//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErro
    {
        public long LogErroID { get; set; }
        public Nullable<long> Importancia { get; set; }
        public string Origem { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string UserName { get; set; }
    }
}
