//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacaoAgendamento
    {
        public long ProgramacaoAgendamentoID { get; set; }
        public long ProgramacaoID { get; set; }
        public long ConteudoID { get; set; }
        public short DiaSemana { get; set; }
        public System.TimeSpan Inicio { get; set; }
        public System.TimeSpan Fim { get; set; }
    
        public virtual Conteudo Conteudo { get; set; }
        public virtual Programacao Programacao { get; set; }
    }
}
