//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programacao()
        {
            this.ProgramacaoAgendamento = new HashSet<ProgramacaoAgendamento>();
            this.Tv = new HashSet<Tv>();
        }
    
        public long ProgramacaoID { get; set; }
        public long EmpresaID { get; set; }
        public string Designacao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramacaoAgendamento> ProgramacaoAgendamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tv> Tv { get; set; }
    }
}
