//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tv
    {
        public long TvID { get; set; }
        public long EmpresaID { get; set; }
        public string Designacao { get; set; }
        public long ProgramacaoID { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Programacao Programacao { get; set; }
    }
}
