//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.BO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Conteudo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Conteudo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SS.CorporateTV.BO.Resources.Conteudo", typeof(Conteudo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Imagem.
        /// </summary>
        public static string AdicionarImagem {
            get {
                return ResourceManager.GetString("AdicionarImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Vídeo.
        /// </summary>
        public static string AdicionarVideo {
            get {
                return ResourceManager.GetString("AdicionarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteudo actualizado..
        /// </summary>
        public static string ConteudoAtualizado {
            get {
                return ResourceManager.GetString("ConteudoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo.
        /// </summary>
        public static string ConteudoTvName {
            get {
                return ResourceManager.GetString("ConteudoTvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        public static string Designacao {
            get {
                return ResourceManager.GetString("Designacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração (minutos).
        /// </summary>
        public static string Duracao {
            get {
                return ResourceManager.GetString("Duracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Uso.
        /// </summary>
        public static string EmUso {
            get {
                return ResourceManager.GetString("EmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        public static string Imagem {
            get {
                return ResourceManager.GetString("Imagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquise por designação.
        /// </summary>
        public static string Pesquisa {
            get {
                return ResourceManager.GetString("Pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Stream.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Imagem.
        /// </summary>
        public static string UrlImagem {
            get {
                return ResourceManager.GetString("UrlImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Vídeo.
        /// </summary>
        public static string UrlVideo {
            get {
                return ResourceManager.GetString("UrlVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeo.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
