//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.BO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SS.CorporateTV.BO.Resources.Erro", typeof(Erro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas ocorreu um erro. Neste momento não tem acesso à página, por favor contacte o administrador de sistema..
        /// </summary>
        public static string Acesso {
            get {
                return ResourceManager.GetString("Acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do registo não são válidos..
        /// </summary>
        public static string DadosIncorrectos {
            get {
                return ResourceManager.GetString("DadosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Designação já existe..
        /// </summary>
        public static string DesignacaoRepetida {
            get {
                return ResourceManager.GetString("DesignacaoRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ter o formato de data (dd/mm/aaaa)..
        /// </summary>
        public static string FormatoData {
            get {
                return ResourceManager.GetString("FormatoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ter o formato de email..
        /// </summary>
        public static string FormatoEmail {
            get {
                return ResourceManager.GetString("FormatoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ter o formato de hora (hh:mm)..
        /// </summary>
        public static string FormatoHora {
            get {
                return ResourceManager.GetString("FormatoHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser um número decimal..
        /// </summary>
        public static string FormatoNumeroDecimal {
            get {
                return ResourceManager.GetString("FormatoNumeroDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser um número inteiro..
        /// </summary>
        public static string FormatoNumeroInteiro {
            get {
                return ResourceManager.GetString("FormatoNumeroInteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deve ser um número inteiro.
        /// </summary>
        public static string FormatoNumeroInteiro2 {
            get {
                return ResourceManager.GetString("FormatoNumeroInteiro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedimos desculpa mas ocorreu um erro, por favor contacte o administrador de sistema..
        /// </summary>
        public static string Geral {
            get {
                return ResourceManager.GetString("Geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser maior que a {1}.
        /// </summary>
        public static string HoraDeveSerInferiorA {
            get {
                return ResourceManager.GetString("HoraDeveSerInferiorA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados do registo não são coerentes..
        /// </summary>
        public static string ModeloInvalido {
            get {
                return ResourceManager.GetString("ModeloInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Nova Password não coincide com a Confirmação..
        /// </summary>
        public static string NovaPasswordDiferenteConfirmacao {
            get {
                return ResourceManager.GetString("NovaPasswordDiferenteConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser entre {1} e {2}..
        /// </summary>
        public static string NumeroEntre {
            get {
                return ResourceManager.GetString("NumeroEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser maior ou igual que {1}..
        /// </summary>
        public static string NumeroMaiorQue {
            get {
                return ResourceManager.GetString("NumeroMaiorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; deve ser menor ou igual que {1}..
        /// </summary>
        public static string NumeroMenorQue {
            get {
                return ResourceManager.GetString("NumeroMenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Password não corresponde à do Utilizador..
        /// </summary>
        public static string PasswordIncorrecta {
            get {
                return ResourceManager.GetString("PasswordIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram adicionadas imagens ao conteúdo..
        /// </summary>
        public static string SemImagens {
            get {
                return ResourceManager.GetString("SemImagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram adicionados vídeos ao conteúdo..
        /// </summary>
        public static string SemVideos {
            get {
                return ResourceManager.GetString("SemVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; pode ter até {1} caracteres..
        /// </summary>
        public static string TamanhoMaximo {
            get {
                return ResourceManager.GetString("TamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string TituloErro {
            get {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O User Name já existe. Seleccione outro por favor..
        /// </summary>
        public static string UserNameRepetido {
            get {
                return ResourceManager.GetString("UserNameRepetido", resourceCulture);
            }
        }
    }
}
