//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.CorporateTV.BO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Programacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Programacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SS.CorporateTV.BO.Resources.Programacao", typeof(Programacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendamento.
        /// </summary>
        public static string Agendamento {
            get {
                return ResourceManager.GetString("Agendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo.
        /// </summary>
        public static string Conteudo {
            get {
                return ResourceManager.GetString("Conteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdos.
        /// </summary>
        public static string Conteudos {
            get {
                return ResourceManager.GetString("Conteudos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        public static string Designacao {
            get {
                return ResourceManager.GetString("Designacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia da Semana.
        /// </summary>
        public static string DiaSemana {
            get {
                return ResourceManager.GetString("DiaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim.
        /// </summary>
        public static string Fim {
            get {
                return ResourceManager.GetString("Fim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Fim.
        /// </summary>
        public static string HoraFim {
            get {
                return ResourceManager.GetString("HoraFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de fim deve ser superior à hora de início..
        /// </summary>
        public static string HoraInferior {
            get {
                return ResourceManager.GetString("HoraInferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora de Início.
        /// </summary>
        public static string InicioStr {
            get {
                return ResourceManager.GetString("InicioStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Pesquisa {
            get {
                return ResourceManager.GetString("Pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programação.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
    }
}
